"""Export original healing/training prices without a runtime DBF dependency.

Run from Big_map with --globals PATH pointing at the game's Globals directory.
--check verifies the checked-in snapshot without modifying it.
"""
from __future__ import annotations

import argparse
from collections import defaultdict
import hashlib
import json
from pathlib import Path
import struct


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "unit_service_cost_data.py"


def read_dbf(path: Path) -> list[dict[str, str]]:
    """Read the character/numeric columns used by the original dBase tables."""
    data = path.read_bytes()
    count, header_size, record_size = struct.unpack_from("<IHH", data, 4)
    fields, offset = [], 1
    for start in range(32, header_size - 1, 32):
        if data[start] == 13:
            break
        name = data[start:start + 11].split(b"\0", 1)[0].decode("ascii")
        size = data[start + 16]
        fields.append((name, offset, size))
        offset += size
    if offset != record_size or len(data) < header_size + count * record_size:
        raise ValueError(f"Invalid DBF record layout: {path}")
    rows = []
    for index in range(count):
        start = header_size + index * record_size
        if data[start:start + 1] == b"*":
            continue
        rows.append({name: data[start + offset:start + offset + size].decode("cp1251").strip()
                     for name, offset, size in fields})
    return rows


def gold_cost(raw: str) -> int:
    amounts = {part[0].lower(): int(part[1:]) for part in raw.split(":")}
    if "g" not in amounts or any(value for key, value in amounts.items() if key != "g"):
        raise ValueError(f"Service price is not gold-only: {raw!r}")
    return amounts["g"]


def load_profiles(globals_dir: Path):
    files = {path.name.lower(): path for path in globals_dir.iterdir() if path.is_file()}
    units = read_dbf(files["gunits.dbf"])
    upgrades = {row["UPGRADE_ID"].lower(): row for row in read_dbf(files["gdynupgr.dbf"])}
    profiles = {}
    for row in units:
        early = upgrades[row["DYN_UPG1"].lower()]
        late = upgrades[row["DYN_UPG2"].lower()]
        profiles[row["UNIT_ID"].lower()] = (
            int(row["LEVEL"]), int(row["DYN_UPG_LV"]),
            *(tuple(gold_cost(source[key]) for key in ("HEAL_C", "TRAINING_C"))
              for source in (row, early, late)),
        )
    hashes = {name: hashlib.sha256(files[name].read_bytes()).hexdigest()
              for name in ("gunits.dbf", "gdynupgr.dbf")}
    return profiles, hashes


def render_data(profiles, hashes) -> str:
    grouped = defaultdict(list)
    for unit_id, profile in sorted(profiles.items()):
        grouped[profile].append(unit_id)
    lines = [
        '"""Original Rise of the Elves Gunits/GDynUpgr service cost snapshot.',
        '',
        'Generated by tools/export_unit_service_costs.py; do not hand-edit prices.',
        'Profile: native level, last early level, base/early/late (gold per HP, gold per XP).',
        '"""', '', 'SOURCE_SHA256 = {',
        *(f'    {name!r}: {digest!r},' for name, digest in hashes.items()),
        '}', '', 'UNIT_SERVICE_COST_PROFILES = {', '    unit_id: profile',
        '    for profile, ids in (',
        *(f'        ({profile!r}, {" ".join(ids)!r}),' for profile, ids in sorted(grouped.items())),
        '    )', '    for unit_id in ids.split()', '}', '',
    ]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--globals", type=Path, dest="globals_dir", default=Path(
        ("C:/" if Path("C:/").exists() else "/mnt/c/")
        + "Program Files (x86)/Steam/steamapps/common/Disciples II Rise of the Elves/Globals"))
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    profiles, hashes = load_profiles(args.globals_dir)
    text = render_data(profiles, hashes)
    if args.check:
        if OUTPUT.read_text(encoding="utf-8") != text:
            raise SystemExit("Service cost snapshot differs from the original DBF tables")
    else:
        OUTPUT.write_text(text, encoding="utf-8")
    print(json.dumps({"profiles": len(profiles), "groups": len(set(profiles.values())),
                      "hashes": hashes,
                      "dynamic_increments": sorted({values for p in profiles.values() for values in p[3:]}),
                      "base_prices": sorted({p[2] for p in profiles.values()})}, indent=2))


if __name__ == "__main__":
    main()
