# Империя (DII)
empire_spells_d2 = {
    "emp_d2_s001": {
        "id": "emp_d2_s001",
        "level": 1,
        "description": "На юнитов, защищённых этим заклинанием, не действует первая в бою атака магии Воздуха (например, молния)",
        "learn_hell": 0,
        "learn_life": 200,
        "learn_death": 0,
        "learn_rune": 0,
        "learn_nature": 0,
        "use_hell": 0,
        "use_life": 100,
        "use_death": 0,
        "use_rune": 0,
        "use_nature": 0,

        "learned": 0,
    },
    "emp_d2_s002": {
        "id": "emp_d2_s002",
        "level": 1,
        "description": "На 10% увеличивает инициативу выбранных юнитов",
        "learn_hell": 0,
        "learn_life": 200,
        "learn_death": 0,
        "learn_rune": 0,
        "learn_nature": 0,
        "use_hell": 0,
        "use_life": 100,
        "use_death": 0,
        "use_rune": 0,
        "use_nature": 0,

        "learned": 0,
    },
    "emp_d2_s003": {
        "id": "emp_d2_s003",
        "level": 1,
        "description": "На 10% увеличивает урон, наносимый зачарованными юнитами в бою",
        "learn_hell": 0,
        "learn_life": 200,
        "learn_death": 0,
        "learn_rune": 0,
        "learn_nature": 0,
        "use_hell": 0,
        "use_life": 100,
        "use_death": 0,
        "use_rune": 0,
        "use_nature": 0,

        "learned": 0,
    },
    "emp_d2_s004": {
        "id": "emp_d2_s004",
        "level": 1,
        "description": "Наносит выбранным юнитам 15 единиц урона магией Воздуха",
        "learn_hell": 0,
        "learn_life": 200,
        "learn_death": 0,
        "learn_rune": 0,
        "learn_nature": 0,
        "use_hell": 0,
        "use_life": 100,
        "use_death": 0,
        "use_rune": 0,
        "use_nature": 0,

        "learned": 0,
    },
    "emp_d2_s005": {
        "id": "emp_d2_s005",
        "level": 1,
        "description": "На юнитов, защищённых этим заклинанием, не действует первая в бою атака магии Воды (например, снежная буря)",
        "learn_hell": 0,
        "learn_life": 200,
        "learn_death": 0,
        "learn_rune": 0,
        "learn_nature": 0,
        "use_hell": 0,
        "use_life": 100,
        "use_death": 0,
        "use_rune": 0,
        "use_nature": 0,

        "learned": 0,
    },
    "emp_d2_s006": {
        "id": "emp_d2_s006",
        "level": 2,
        "description": "Под воздействием этого заклинания юниты восстанавливают 50% единиц движения",
        "learn_hell": 0,
        "learn_life": 400,
        "learn_death": 0,
        "learn_rune": 0,
        "learn_nature": 0,
        "use_hell": 0,
        "use_life": 200,
        "use_death": 0,
        "use_rune": 0,
        "use_nature": 0,

        "learned": 0,
    },
    "emp_d2_s007": {
        "id": "emp_d2_s007",
        "level": 2,
        "description": "Восстанавливает 30 единиц здоровья",
        "learn_hell": 0,
        "learn_life": 400,
        "learn_death": 0,
        "learn_rune": 0,
        "learn_nature": 0,
        "use_hell": 0,
        "use_life": 200,
        "use_death": 0,
        "use_rune": 0,
        "use_nature": 0,

        "learned": 0,
    },
    "emp_d2_s008": {
        "id": "emp_d2_s008",
        "level": 2,
        "description": "Призывает оживлённый волшебством доспех",
        "learn_hell": 0,
        "learn_life": 400,
        "learn_death": 0,
        "learn_rune": 0,
        "learn_nature": 0,
        "use_hell": 0,
        "use_life": 200,
        "use_death": 0,
        "use_rune": 0,
        "use_nature": 0,

        "learned": 0,
    },
    "emp_d2_s009": {
        "id": "emp_d2_s009",
        "level": 2,
        "description": "Рассеивает туман войны на небольшой площади",
        "learn_hell": 0,
        "learn_life": 400,
        "learn_death": 0,
        "learn_rune": 0,
        "learn_nature": 0,
        "use_hell": 0,
        "use_life": 200,
        "use_death": 0,
        "use_rune": 0,
        "use_nature": 0,

        "learned": 0,
    },
    "emp_d2_s010": {
        "id": "emp_d2_s010",
        "level": 2,
        "description": "На юнитов, защищённых этим заклинанием, не действует первая в бою атака магии Земли (например, земляной столп)",
        "learn_hell": 0,
        "learn_life": 400,
        "learn_death": 0,
        "learn_rune": 0,
        "learn_nature": 0,
        "use_hell": 0,
        "use_life": 200,
        "use_death": 0,
        "use_rune": 0,
        "use_nature": 0,

        "learned": 0,
    },
    "emp_d2_s011": {
        "id": "emp_d2_s011",
        "level": 3,
        "description": "На юнитов, защищённых этим заклинанием, не действует первая в бою атака магии Разума (например, паралич)",
        "learn_hell": 0,
        "learn_life": 450,
        "learn_death": 0,
        "learn_rune": 450,
        "learn_nature": 0,
        "use_hell": 0,
        "use_life": 150,
        "use_death": 0,
        "use_rune": 150,
        "use_nature": 0,

        "learned": 0,
    },
    "emp_d2_s012": {
        "id": "emp_d2_s012",
        "level": 3,
        "description": "Под воздействием этого заклинания получаемый юнитами урон уменьшается на 20%",
        "learn_hell": 0,
        "learn_life": 450,
        "learn_death": 0,
        "learn_rune": 450,
        "learn_nature": 0,
        "use_hell": 0,
        "use_life": 150,
        "use_death": 0,
        "use_rune": 150,
        "use_nature": 0,

        "learned": 0,
    },
    "emp_d2_s013": {
        "id": "emp_d2_s013",
        "level": 3,
        "description": "На 20% увеличивает шанс юнитов попасть по противнику",
        "learn_hell": 450,
        "learn_life": 450,
        "learn_death": 0,
        "learn_rune": 0,
        "learn_nature": 0,
        "use_hell": 150,
        "use_life": 150,
        "use_death": 0,
        "use_rune": 0,
        "use_nature": 0,

        "learned": 0,
    },
    "emp_d2_s014": {
        "id": "emp_d2_s014",
        "level": 3,
        "description": "Наносит выбранным юнитам 50 единиц урона магией Воздуха",
        "learn_hell": 0,
        "learn_life": 450,
        "learn_death": 0,
        "learn_rune": 450,
        "learn_nature": 0,
        "use_hell": 0,
        "use_life": 150,
        "use_death": 0,
        "use_rune": 150,
        "use_nature": 0,

        "learned": 0,
    },
    "emp_d2_s015": {
        "id": "emp_d2_s015",
        "level": 3,
        "description": "Наносит 40 единиц урона магией Воздуха в центр площади заклинания",
        "learn_hell": 0,
        "learn_life": 680,
        "learn_death": 0,
        "learn_rune": 680,
        "learn_nature": 0,
        "use_hell": 0,
        "use_life": 225,
        "use_death": 0,
        "use_rune": 225,
        "use_nature": 0,

        "learned": 0,
    },
    "emp_d2_s016": {
        "id": "emp_d2_s016",
        "level": 4,
        "description": "Призывает голема-элементаля Земли",
        "learn_hell": 400,
        "learn_life": 800,
        "learn_death": 0,
        "learn_rune": 400,
        "learn_nature": 0,
        "use_hell": 100,
        "use_life": 200,
        "use_death": 0,
        "use_rune": 100,
        "use_nature": 0,

        "learned": 0,
    },
    "emp_d2_s017": {
        "id": "emp_d2_s017",
        "level": 4,
        "description": "На юнитов, защищённых этим заклинанием, не действует первая в бою атака магии Огня (например, огненный шар)",
        "learn_hell": 600,
        "learn_life": 800,
        "learn_death": 0,
        "learn_rune": 300,
        "learn_nature": 0,
        "use_hell": 125,
        "use_life": 200,
        "use_death": 0,
        "use_rune": 75,
        "use_nature": 0,

        "learned": 0,
    },
    "emp_d2_s018": {
        "id": "emp_d2_s018",
        "level": 4,
        "description": "На 33% увеличивает урон, наносимый зачарованными юнитами в бою",
        "learn_hell": 400,
        "learn_life": 800,
        "learn_death": 0,
        "learn_rune": 400,
        "learn_nature": 0,
        "use_hell": 100,
        "use_life": 200,
        "use_death": 0,
        "use_rune": 100,
        "use_nature": 0,

        "learned": 0,
    },
    "emp_d2_s019": {
        "id": "emp_d2_s019",
        "level": 4,
        "description": "Восстанавливает 60 единиц здоровья в центре зоны действия заклинания",
        "learn_hell": 600,
        "learn_life": 1200,
        "learn_death": 0,
        "learn_rune": 600,
        "learn_nature": 0,
        "use_hell": 150,
        "use_life": 300,
        "use_death": 0,
        "use_rune": 150,
        "use_nature": 0,

        "learned": 0,
    },
    "emp_d2_s020": {
        "id": "emp_d2_s020",
        "level": 4,
        "description": "Рассеивает весь туман войны",
        "learn_hell": 800,
        "learn_life": 1600,
        "learn_death": 0,
        "learn_rune": 800,
        "learn_nature": 0,
        "use_hell": 200,
        "use_life": 400,
        "use_death": 0,
        "use_rune": 200,
        "use_nature": 0,

        "learned": 0,
    },
    "emp_d2_s021": {
        "id": "emp_d2_s021",
        "level": 5,
        "description": "На юнитов, защищённых этим заклинанием, не действует первая в бою атака магии Смерти (например, чума)",
        "learn_hell": 150,
        "learn_life": 625,
        "learn_death": 300,
        "learn_rune": 175,
        "learn_nature": 0,
        "use_hell": 60,
        "use_life": 250,
        "use_death": 120,
        "use_rune": 70,
        "use_nature": 0,

        "learned": 0,
    },
    "emp_d2_s022": {
        "id": "emp_d2_s022",
        "level": 5,
        "description": "Наносит выбранным юнитам 125 единиц урона магией Воздуха",
        "learn_hell": 250,
        "learn_life": 625,
        "learn_death": 200,
        "learn_rune": 175,
        "learn_nature": 0,
        "use_hell": 70,
        "use_life": 250,
        "use_death": 80,
        "use_rune": 100,
        "use_nature": 0,

        "learned": 0,
    },
    "emp_d2_s023": {
        "id": "emp_d2_s023",
        "level": 5,
        "description": "Восстанавливает 150 единиц здоровья",
        "learn_hell": 225,
        "learn_life": 625,
        "learn_death": 150,
        "learn_rune": 250,
        "learn_nature": 0,
        "use_hell": 100,
        "use_life": 250,
        "use_death": 60,
        "use_rune": 100,
        "use_nature": 0,

        "learned": 0,
    },
    "emp_d2_s024": {
        "id": "emp_d2_s024",
        "level": 5,
        "description": "Восстанавливает 80 единиц здоровья всем юнитам заклинателя",
        "learn_hell": 400,
        "learn_life": 1250,
        "learn_death": 400,
        "learn_rune": 450,
        "learn_nature": 0,
        "use_hell": 160,
        "use_life": 500,
        "use_death": 160,
        "use_rune": 180,
        "use_nature": 0,

        "learned": 0,
    },
}


# Горные Кланы (DII)
mountain_clans_spells_d2 = {
    "mcl_d2_s001": {
        "id": "mcl_d2_s001",
        "level": 1,
        "description": "Под действием этого заклинания получаемый юнитами урон уменьшается на 10%",
        "learn_hell": 0,
        "learn_life": 0,
        "learn_death": 0,
        "learn_rune": 200,
        "learn_nature": 0,
        "use_hell": 0,
        "use_life": 0,
        "use_death": 0,
        "use_rune": 100,
        "use_nature": 0,

        "learned": 0,
    },
    "mcl_d2_s002": {
        "id": "mcl_d2_s002",
        "level": 1,
        "description": "Выбранный отряд будет передвигаться по лесу с максимальной скоростью",
        "learn_hell": 0,
        "learn_life": 0,
        "learn_death": 0,
        "learn_rune": 100,
        "learn_nature": 0,
        "use_hell": 0,
        "use_life": 0,
        "use_death": 0,
        "use_rune": 25,
        "use_nature": 0,

        "learned": 0,
    },
    "mcl_d2_s003": {
        "id": "mcl_d2_s003",
        "level": 1,
        "description": "На 10% увеличивает урон, наносимый зачарованными юнитами в бою",
        "learn_hell": 0,
        "learn_life": 0,
        "learn_death": 0,
        "learn_rune": 200,
        "learn_nature": 0,
        "use_hell": 0,
        "use_life": 0,
        "use_death": 0,
        "use_rune": 100,
        "use_nature": 0,

        "learned": 0,
    },
    "mcl_d2_s004": {
        "id": "mcl_d2_s004",
        "level": 1,
        "description": "Наносит выбранным юнитам 15 единиц урона магией Воды",
        "learn_hell": 0,
        "learn_life": 0,
        "learn_death": 0,
        "learn_rune": 200,
        "learn_nature": 0,
        "use_hell": 0,
        "use_life": 0,
        "use_death": 0,
        "use_rune": 100,
        "use_nature": 0,

        "learned": 0,
    },
    "mcl_d2_s005": {
        "id": "mcl_d2_s005",
        "level": 1,
        "description": "Призывает летающую птицу Рух",
        "learn_hell": 0,
        "learn_life": 0,
        "learn_death": 0,
        "learn_rune": 200,
        "learn_nature": 0,
        "use_hell": 0,
        "use_life": 0,
        "use_death": 0,
        "use_rune": 100,
        "use_nature": 0,

        "learned": 0,
    },
    "mcl_d2_s006": {
        "id": "mcl_d2_s006",
        "level": 2,
        "description": "На 15% увеличивает инициативу выбранных юнитов",
        "learn_hell": 0,
        "learn_life": 0,
        "learn_death": 0,
        "learn_rune": 400,
        "learn_nature": 0,
        "use_hell": 0,
        "use_life": 0,
        "use_death": 0,
        "use_rune": 200,
        "use_nature": 0,

        "learned": 0,
    },
    "mcl_d2_s007": {
        "id": "mcl_d2_s007",
        "level": 2,
        "description": "Выбранный отряд будет передвигаться по воде с максимальной скоростью",
        "learn_hell": 0,
        "learn_life": 0,
        "learn_death": 0,
        "learn_rune": 200,
        "learn_nature": 0,
        "use_hell": 0,
        "use_life": 0,
        "use_death": 0,
        "use_rune": 50,
        "use_nature": 0,

        "learned": 0,
    },
    "mcl_d2_s008": {
        "id": "mcl_d2_s008",
        "level": 2,
        "description": "Наносит выбранным юнитам 30 единиц урона магией Воды",
        "learn_hell": 0,
        "learn_life": 0,
        "learn_death": 0,
        "learn_rune": 400,
        "learn_nature": 0,
        "use_hell": 0,
        "use_life": 0,
        "use_death": 0,
        "use_rune": 200,
        "use_nature": 0,

        "learned": 0,
    },
    "mcl_d2_s009": {
        "id": "mcl_d2_s009",
        "level": 2,
        "description": "Восстанавливает 30 единиц здоровья",
        "learn_hell": 0,
        "learn_life": 0,
        "learn_death": 0,
        "learn_rune": 400,
        "learn_nature": 0,
        "use_hell": 0,
        "use_life": 0,
        "use_death": 0,
        "use_rune": 200,
        "use_nature": 0,

        "learned": 0,
    },
    "mcl_d2_s010": {
        "id": "mcl_d2_s010",
        "level": 2,
        "description": "Рассеивает туман войны на небольшой площади",
        "learn_hell": 0,
        "learn_life": 0,
        "learn_death": 0,
        "learn_rune": 400,
        "learn_nature": 0,
        "use_hell": 0,
        "use_life": 0,
        "use_death": 0,
        "use_rune": 200,
        "use_nature": 0,

        "learned": 0,
    },
    "mcl_d2_s011": {
        "id": "mcl_d2_s011",
        "level": 3,
        "description": "Призывает валькирию",
        "learn_hell": 0,
        "learn_life": 450,
        "learn_death": 0,
        "learn_rune": 450,
        "learn_nature": 0,
        "use_hell": 0,
        "use_life": 150,
        "use_death": 0,
        "use_rune": 150,
        "use_nature": 0,

        "learned": 0,
    },
    "mcl_d2_s012": {
        "id": "mcl_d2_s012",
        "level": 3,
        "description": "Под воздействием этого заклинания юниты восстанавливают 100% единиц движения",
        "learn_hell": 0,
        "learn_life": 0,
        "learn_death": 300,
        "learn_rune": 300,
        "learn_nature": 0,
        "use_hell": 0,
        "use_life": 0,
        "use_death": 75,
        "use_rune": 75,
        "use_nature": 0,

        "learned": 0,
    },
    "mcl_d2_s013": {
        "id": "mcl_d2_s013",
        "level": 3,
        "description": "Наносит выбранным юнитам 60 единиц урона магией Земли",
        "learn_hell": 0,
        "learn_life": 450,
        "learn_death": 0,
        "learn_rune": 450,
        "learn_nature": 0,
        "use_hell": 0,
        "use_life": 150,
        "use_death": 0,
        "use_rune": 150,
        "use_nature": 0,

        "learned": 0,
    },
    "mcl_d2_s014": {
        "id": "mcl_d2_s014",
        "level": 3,
        "description": "На 25% увеличивает шанс юнитов попасть по противнику",
        "learn_hell": 0,
        "learn_life": 450,
        "learn_death": 0,
        "learn_rune": 450,
        "learn_nature": 0,
        "use_hell": 0,
        "use_life": 150,
        "use_death": 0,
        "use_rune": 150,
        "use_nature": 0,

        "learned": 0,
    },
    "mcl_d2_s015": {
        "id": "mcl_d2_s015",
        "level": 3,
        "description": "На 20% увеличивает урон, наносимый юнитами в бою",
        "learn_hell": 0,
        "learn_life": 680,
        "learn_death": 0,
        "learn_rune": 680,
        "learn_nature": 0,
        "use_hell": 0,
        "use_life": 150,
        "use_death": 0,
        "use_rune": 150,
        "use_nature": 0,

        "learned": 0,
    },
    "mcl_d2_s016": {
        "id": "mcl_d2_s016",
        "level": 4,
        "description": "Под воздействием этого заклинания получаемый юнитами урон уменьшается на 33%",
        "learn_hell": 0,
        "learn_life": 300,
        "learn_death": 500,
        "learn_rune": 800,
        "learn_nature": 0,
        "use_hell": 0,
        "use_life": 75,
        "use_death": 125,
        "use_rune": 200,
        "use_nature": 0,

        "learned": 0,
    },
    "mcl_d2_s017": {
        "id": "mcl_d2_s017",
        "level": 4,
        "description": "На 33% увеличивает шанс юнитов попасть по противнику",
        "learn_hell": 0,
        "learn_life": 400,
        "learn_death": 400,
        "learn_rune": 800,
        "learn_nature": 0,
        "use_hell": 0,
        "use_life": 100,
        "use_death": 100,
        "use_rune": 200,
        "use_nature": 0,

        "learned": 0,
    },
    "mcl_d2_s018": {
        "id": "mcl_d2_s018",
        "level": 4,
        "description": "Наносит выбранным юнитам 75 единиц урона магией Воды",
        "learn_hell": 0,
        "learn_life": 400,
        "learn_death": 400,
        "learn_rune": 800,
        "learn_nature": 0,
        "use_hell": 0,
        "use_life": 100,
        "use_death": 100,
        "use_rune": 200,
        "use_nature": 0,

        "learned": 0,
    },
    "mcl_d2_s019": {
        "id": "mcl_d2_s019",
        "level": 4,
        "description": "Наносит 60 единиц урона магией Воды в центр площади заклинания",
        "learn_hell": 0,
        "learn_life": 600,
        "learn_death": 600,
        "learn_rune": 1200,
        "learn_nature": 0,
        "use_hell": 0,
        "use_life": 150,
        "use_death": 150,
        "use_rune": 300,
        "use_nature": 0,

        "learned": 0,
    },
    "mcl_d2_s020": {
        "id": "mcl_d2_s020",
        "level": 4,
        "description": "Восстанавливает 100% единиц движения всем юнитам заклинателя",
        "learn_hell": 0,
        "learn_life": 800,
        "learn_death": 800,
        "learn_rune": 1600,
        "learn_nature": 0,
        "use_hell": 0,
        "use_life": 400,
        "use_death": 400,
        "use_rune": 800,
        "use_nature": 0,

        "learned": 0,
    },
    "mcl_d2_s021": {
        "id": "mcl_d2_s021",
        "level": 5,
        "description": "Призывает каменного предка гномов",
        "learn_hell": 300,
        "learn_life": 175,
        "learn_death": 150,
        "learn_rune": 625,
        "learn_nature": 0,
        "use_hell": 120,
        "use_life": 70,
        "use_death": 60,
        "use_rune": 250,
        "use_nature": 0,

        "learned": 0,
    },
    "mcl_d2_s022": {
        "id": "mcl_d2_s022",
        "level": 5,
        "description": "Под воздействием этого заклинания юниты становятся невосприимчивы к манипуляциям вражеских воров",
        "learn_hell": 200,
        "learn_life": 250,
        "learn_death": 175,
        "learn_rune": 625,
        "learn_nature": 0,
        "use_hell": 80,
        "use_life": 100,
        "use_death": 70,
        "use_rune": 250,
        "use_nature": 0,

        "learned": 0,
    },
    "mcl_d2_s023": {
        "id": "mcl_d2_s023",
        "level": 5,
        "description": "На 50% увеличивает урон, наносимый зачарованными юнитами в бою",
        "learn_hell": 150,
        "learn_life": 275,
        "learn_death": 200,
        "learn_rune": 625,
        "learn_nature": 0,
        "use_hell": 60,
        "use_life": 110,
        "use_death": 80,
        "use_rune": 250,
        "use_nature": 0,

        "learned": 0,
    },
    "mcl_d2_s024": {
        "id": "mcl_d2_s024",
        "level": 5,
        "description": "Усиливает броню всех юнитов заклинателя на 33",
        "learn_hell": 400,
        "learn_life": 450,
        "learn_death": 400,
        "learn_rune": 1250,
        "learn_nature": 0,
        "use_hell": 160,
        "use_life": 180,
        "use_death": 160,
        "use_rune": 500,
        "use_nature": 0,

        "learned": 0,
    },
}


# Орды Нежити (DII)
undead_hordes_spells_d2 = {
    "und_d2_s001": {
        "id": "und_d2_s001",
        "level": 1,
        "description": "Призывает скелета",
        "learn_hell": 0,
        "learn_life": 0,
        "learn_death": 200,
        "learn_rune": 0,
        "learn_nature": 0,
        "use_hell": 0,
        "use_life": 0,
        "use_death": 100,
        "use_rune": 0,
        "use_nature": 0,

        "learned": 0,
    },
    "und_d2_s002": {
        "id": "und_d2_s002",
        "level": 1,
        "description": "Наносит выбранным юнитам 15 единиц урона магией Смерти",
        "learn_hell": 0,
        "learn_life": 0,
        "learn_death": 200,
        "learn_rune": 0,
        "learn_nature": 0,
        "use_hell": 0,
        "use_life": 0,
        "use_death": 100,
        "use_rune": 0,
        "use_nature": 0,

        "learned": 0,
    },
    "und_d2_s003": {
        "id": "und_d2_s003",
        "level": 1,
        "description": "Наносит выбранным юнитам 15 единиц урона магией Воды",
        "learn_hell": 0,
        "learn_life": 0,
        "learn_death": 200,
        "learn_rune": 0,
        "learn_nature": 0,
        "use_hell": 0,
        "use_life": 0,
        "use_death": 100,
        "use_rune": 0,
        "use_nature": 0,

        "learned": 0,
    },
    "und_d2_s004": {
        "id": "und_d2_s004",
        "level": 1,
        "description": "На 10% снижает шанс юнитов попасть по противнику",
        "learn_hell": 0,
        "learn_life": 0,
        "learn_death": 200,
        "learn_rune": 0,
        "learn_nature": 0,
        "use_hell": 0,
        "use_life": 0,
        "use_death": 100,
        "use_rune": 0,
        "use_nature": 0,

        "learned": 0,
    },
    "und_d2_s005": {
        "id": "und_d2_s005",
        "level": 1,
        "description": "Уменьшает броню выбранных юнитов на 50%",
        "learn_hell": 0,
        "learn_life": 0,
        "learn_death": 200,
        "learn_rune": 0,
        "learn_nature": 0,
        "use_hell": 0,
        "use_life": 0,
        "use_death": 100,
        "use_rune": 0,
        "use_nature": 0,

        "learned": 0,
    },
    "und_d2_s006": {
        "id": "und_d2_s006",
        "level": 2,
        "description": "Призывает злого энта",
        "learn_hell": 0,
        "learn_life": 0,
        "learn_death": 400,
        "learn_rune": 0,
        "learn_nature": 0,
        "use_hell": 0,
        "use_life": 0,
        "use_death": 200,
        "use_rune": 0,
        "use_nature": 0,

        "learned": 0,
    },
    "und_d2_s007": {
        "id": "und_d2_s007",
        "level": 2,
        "description": "Наносит выбранным воинам 30 единиц урона магией Смерти",
        "learn_hell": 0,
        "learn_life": 0,
        "learn_death": 400,
        "learn_rune": 0,
        "learn_nature": 0,
        "use_hell": 0,
        "use_life": 0,
        "use_death": 200,
        "use_rune": 0,
        "use_nature": 0,

        "learned": 0,
    },
    "und_d2_s008": {
        "id": "und_d2_s008",
        "level": 2,
        "description": "Восстанавливает на небольшой площади туман войны, который защищает отряд от вражеских заклинаний",
        "learn_hell": 0,
        "learn_life": 0,
        "learn_death": 400,
        "learn_rune": 0,
        "learn_nature": 0,
        "use_hell": 0,
        "use_life": 0,
        "use_death": 200,
        "use_rune": 0,
        "use_nature": 0,

        "learned": 0,
    },
    "und_d2_s009": {
        "id": "und_d2_s009",
        "level": 2,
        "description": "Уменьшает урон, наносимый юнитами в бою, на 15%",
        "learn_hell": 0,
        "learn_life": 0,
        "learn_death": 400,
        "learn_rune": 0,
        "learn_nature": 0,
        "use_hell": 0,
        "use_life": 0,
        "use_death": 200,
        "use_rune": 0,
        "use_nature": 0,

        "learned": 0,
    },
    "und_d2_s010": {
        "id": "und_d2_s010",
        "level": 2,
        "description": "Наносит выбранным воинам 30 единиц урона магией Земли",
        "learn_hell": 0,
        "learn_life": 0,
        "learn_death": 400,
        "learn_rune": 0,
        "learn_nature": 0,
        "use_hell": 0,
        "use_life": 0,
        "use_death": 200,
        "use_rune": 0,
        "use_nature": 0,

        "learned": 0,
    },
    "und_d2_s011": {
        "id": "und_d2_s011",
        "level": 3,
        "description": "Призывает кошмара",
        "learn_hell": 450,
        "learn_life": 0,
        "learn_death": 450,
        "learn_rune": 0,
        "learn_nature": 0,
        "use_hell": 150,
        "use_life": 0,
        "use_death": 150,
        "use_rune": 0,
        "use_nature": 0,

        "learned": 0,
    },
    "und_d2_s012": {
        "id": "und_d2_s012",
        "level": 3,
        "description": "Наносит выбранным юнитам 50 единиц урона магией Смерти",
        "learn_hell": 0,
        "learn_life": 0,
        "learn_death": 450,
        "learn_rune": 450,
        "learn_nature": 0,
        "use_hell": 0,
        "use_life": 0,
        "use_death": 150,
        "use_rune": 150,
        "use_nature": 0,

        "learned": 0,
    },
    "und_d2_s013": {
        "id": "und_d2_s013",
        "level": 3,
        "description": "На 20% снижает шанс юнитов попасть по противнику",
        "learn_hell": 450,
        "learn_life": 0,
        "learn_death": 450,
        "learn_rune": 0,
        "learn_nature": 0,
        "use_hell": 150,
        "use_life": 0,
        "use_death": 150,
        "use_rune": 0,
        "use_nature": 0,

        "learned": 0,
    },
    "und_d2_s014": {
        "id": "und_d2_s014",
        "level": 3,
        "description": "Восстанавливает на большой площади туман войны, который защищает отряд от вражеских заклинаний",
        "learn_hell": 450,
        "learn_life": 0,
        "learn_death": 450,
        "learn_rune": 0,
        "learn_nature": 0,
        "use_hell": 150,
        "use_life": 0,
        "use_death": 150,
        "use_rune": 0,
        "use_nature": 0,

        "learned": 0,
    },
    "und_d2_s015": {
        "id": "und_d2_s015",
        "level": 3,
        "description": "Наносит 40 единиц урона магией Земли в центр площади заклинания",
        "learn_hell": 680,
        "learn_life": 0,
        "learn_death": 680,
        "learn_rune": 0,
        "learn_nature": 0,
        "use_hell": 225,
        "use_life": 0,
        "use_death": 225,
        "use_rune": 0,
        "use_nature": 0,

        "learned": 0,
    },
    "und_d2_s016": {
        "id": "und_d2_s016",
        "level": 4,
        "description": "На 33% снижает инициативу выбранных юнитов",
        "learn_hell": 400,
        "learn_life": 0,
        "learn_death": 800,
        "learn_rune": 400,
        "learn_nature": 0,
        "use_hell": 100,
        "use_life": 0,
        "use_death": 200,
        "use_rune": 100,
        "use_nature": 0,

        "learned": 0,
    },
    "und_d2_s017": {
        "id": "und_d2_s017",
        "level": 4,
        "description": "Уменьшает урон, наносимый юнитами в бою, на 33%",
        "learn_hell": 400,
        "learn_life": 0,
        "learn_death": 800,
        "learn_rune": 400,
        "learn_nature": 0,
        "use_hell": 100,
        "use_life": 0,
        "use_death": 200,
        "use_rune": 100,
        "use_nature": 0,

        "learned": 0,
    },
    "und_d2_s018": {
        "id": "und_d2_s018",
        "level": 4,
        "description": "Наносит выбранным юнитам 75 единиц урона магией Огня",
        "learn_hell": 500,
        "learn_life": 0,
        "learn_death": 800,
        "learn_rune": 300,
        "learn_nature": 0,
        "use_hell": 125,
        "use_life": 0,
        "use_death": 200,
        "use_rune": 75,
        "use_nature": 0,

        "learned": 0,
    },
    "und_d2_s019": {
        "id": "und_d2_s019",
        "level": 4,
        "description": "На 50% уменьшает количество единиц движения всем юнитам в зоне действия заклинания",
        "learn_hell": 600,
        "learn_life": 0,
        "learn_death": 1200,
        "learn_rune": 600,
        "learn_nature": 0,
        "use_hell": 200,
        "use_life": 0,
        "use_death": 400,
        "use_rune": 200,
        "use_nature": 0,

        "learned": 0,
    },
    "und_d2_s020": {
        "id": "und_d2_s020",
        "level": 4,
        "description": "Сгущает туман войны всем противникам",
        "learn_hell": 0,
        "learn_life": 800,
        "learn_death": 1600,
        "learn_rune": 800,
        "learn_nature": 0,
        "use_hell": 0,
        "use_life": 200,
        "use_death": 400,
        "use_rune": 200,
        "use_nature": 0,

        "learned": 0,
    },
    "und_d2_s021": {
        "id": "und_d2_s021",
        "level": 5,
        "description": "Призывает танатоса",
        "learn_hell": 250,
        "learn_life": 150,
        "learn_death": 625,
        "learn_rune": 225,
        "learn_nature": 0,
        "use_hell": 100,
        "use_life": 60,
        "use_death": 250,
        "use_rune": 90,
        "use_nature": 0,

        "learned": 0,
    },
    "und_d2_s022": {
        "id": "und_d2_s022",
        "level": 5,
        "description": "На юнитов, защищённых этим заклинанием, не действует первая в бою атака оружием (например, мечом)",
        "learn_hell": 175,
        "learn_life": 250,
        "learn_death": 625,
        "learn_rune": 200,
        "learn_nature": 0,
        "use_hell": 70,
        "use_life": 100,
        "use_death": 250,
        "use_rune": 80,
        "use_nature": 0,

        "learned": 0,
    },
    "und_d2_s023": {
        "id": "und_d2_s023",
        "level": 5,
        "description": "Наносит выбранным юнитам 125 единиц урона магией Смерти",
        "learn_hell": 250,
        "learn_life": 200,
        "learn_death": 625,
        "learn_rune": 175,
        "learn_nature": 0,
        "use_hell": 100,
        "use_life": 82,
        "use_death": 250,
        "use_rune": 70,
        "use_nature": 0,

        "learned": 0,
    },
    "und_d2_s024": {
        "id": "und_d2_s024",
        "level": 5,
        "description": "Наносит 80 единиц урона магией Смерти в центр площади заклинания",
        "learn_hell": 340,
        "learn_life": 300,
        "learn_death": 940,
        "learn_rune": 300,
        "learn_nature": 0,
        "use_hell": 135,
        "use_life": 120,
        "use_death": 375,
        "use_rune": 120,
        "use_nature": 0,

        "learned": 0,
    },
}


# Легионы Проклятых (DII)
legions_spells_d2 = {
    "lod_d2_s001": {
        "id": "lod_d2_s001",
        "level": 1,
        "description": "Призыв огнедышащей адской гончей",
        "learn_hell": 200,
        "learn_life": 0,
        "learn_death": 0,
        "learn_rune": 0,
        "learn_nature": 0,
        "use_hell": 100,
        "use_life": 0,
        "use_death": 0,
        "use_rune": 0,
        "use_nature": 0,

        "learned": 0,
    },
    "lod_d2_s002": {
        "id": "lod_d2_s002",
        "level": 1,
        "description": "Призыв иллюзии адской гончей",
        "learn_hell": 150,
        "learn_life": 0,
        "learn_death": 0,
        "learn_rune": 0,
        "learn_nature": 0,
        "use_hell": 50,
        "use_life": 0,
        "use_death": 0,
        "use_rune": 0,
        "use_nature": 0,

        "learned": 0,
    },
    "lod_d2_s003": {
        "id": "lod_d2_s003",
        "level": 1,
        "description": "15 урона огнем",
        "learn_hell": 200,
        "learn_life": 0,
        "learn_death": 0,
        "learn_rune": 0,
        "learn_nature": 0,
        "use_hell": 100,
        "use_life": 0,
        "use_death": 0,
        "use_rune": 0,
        "use_nature": 0,

        "learned": 0,
    },
    "lod_d2_s004": {
        "id": "lod_d2_s004",
        "level": 1,
        "description": "15 урона разумом",
        "learn_hell": 200,
        "learn_life": 0,
        "learn_death": 0,
        "learn_rune": 0,
        "learn_nature": 0,
        "use_hell": 100,
        "use_life": 0,
        "use_death": 0,
        "use_rune": 0,
        "use_nature": 0,

        "learned": 0,
    },
    "lod_d2_s005": {
        "id": "lod_d2_s005",
        "level": 1,
        "description": "-50% брони",
        "learn_hell": 200,
        "learn_life": 0,
        "learn_death": 0,
        "learn_rune": 0,
        "learn_nature": 0,
        "use_hell": 100,
        "use_life": 0,
        "use_death": 0,
        "use_rune": 0,
        "use_nature": 0,

        "learned": 0,
    },
    "lod_d2_s006": {
        "id": "lod_d2_s006",
        "level": 2,
        "description": "Призыв Белиарха",
        "learn_hell": 400,
        "learn_life": 0,
        "learn_death": 0,
        "learn_rune": 0,
        "learn_nature": 0,
        "use_hell": 200,
        "use_life": 0,
        "use_death": 0,
        "use_rune": 0,
        "use_nature": 0,

        "learned": 0,
    },
    "lod_d2_s007": {
        "id": "lod_d2_s007",
        "level": 2,
        "description": "Призыв иллюзии Белиарха",
        "learn_hell": 300,
        "learn_life": 0,
        "learn_death": 0,
        "learn_rune": 0,
        "learn_nature": 0,
        "use_hell": 100,
        "use_life": 0,
        "use_death": 0,
        "use_rune": 0,
        "use_nature": 0,

        "learned": 0,
    },
    "lod_d2_s008": {
        "id": "lod_d2_s008",
        "level": 2,
        "description": "30 урона огнем",
        "learn_hell": 400,
        "learn_life": 0,
        "learn_death": 0,
        "learn_rune": 0,
        "learn_nature": 0,
        "use_hell": 200,
        "use_life": 0,
        "use_death": 0,
        "use_rune": 0,
        "use_nature": 0,

        "learned": 0,
    },
    "lod_d2_s009": {
        "id": "lod_d2_s009",
        "level": 2,
        "description": "-15% к урону",
        "learn_hell": 400,
        "learn_life": 0,
        "learn_death": 0,
        "learn_rune": 0,
        "learn_nature": 0,
        "use_hell": 200,
        "use_life": 0,
        "use_death": 0,
        "use_rune": 0,
        "use_nature": 0,

        "learned": 0,
    },
    "lod_d2_s010": {
        "id": "lod_d2_s010",
        "level": 2,
        "description": "-15% к инициативе",
        "learn_hell": 400,
        "learn_life": 0,
        "learn_death": 0,
        "learn_rune": 0,
        "learn_nature": 0,
        "use_hell": 200,
        "use_life": 0,
        "use_death": 0,
        "use_rune": 0,
        "use_nature": 0,

        "learned": 0,
    },
    "lod_d2_s011": {
        "id": "lod_d2_s011",
        "level": 3,
        "description": "Невидимость отряда до действия",
        "learn_hell": 450,
        "learn_life": 450,
        "learn_death": 0,
        "learn_rune": 0,
        "learn_nature": 0,
        "use_hell": 150,
        "use_life": 150,
        "use_death": 0,
        "use_rune": 0,
        "use_nature": 0,

        "learned": 0,
    },
    "lod_d2_s012": {
        "id": "lod_d2_s012",
        "level": 3,
        "description": "Возвращает туман войны",
        "learn_hell": 450,
        "learn_life": 0,
        "learn_death": 450,
        "learn_rune": 0,
        "learn_nature": 0,
        "use_hell": 150,
        "use_life": 0,
        "use_death": 150,
        "use_rune": 0,
        "use_nature": 0,

        "learned": 0,
    },
    "lod_d2_s013": {
        "id": "lod_d2_s013",
        "level": 3,
        "description": "Паралич на день, -100% движения",
        "learn_hell": 450,
        "learn_life": 0,
        "learn_death": 450,
        "learn_rune": 0,
        "learn_nature": 0,
        "use_hell": 150,
        "use_life": 0,
        "use_death": 150,
        "use_rune": 0,
        "use_nature": 0,

        "learned": 0,
    },
    "lod_d2_s014": {
        "id": "lod_d2_s014",
        "level": 3,
        "description": "50 урона разумом",
        "learn_hell": 450,
        "learn_life": 0,
        "learn_death": 450,
        "learn_rune": 0,
        "learn_nature": 0,
        "use_hell": 150,
        "use_life": 0,
        "use_death": 150,
        "use_rune": 0,
        "use_nature": 0,

        "learned": 0,
    },
    "lod_d2_s015": {
        "id": "lod_d2_s015",
        "level": 3,
        "description": "-25% к шансу попадания",
        "learn_hell": 680,
        "learn_life": 0,
        "learn_death": 680,
        "learn_rune": 0,
        "learn_nature": 0,
        "use_hell": 225,
        "use_life": 0,
        "use_death": 225,
        "use_rune": 0,
        "use_nature": 0,

        "learned": 0,
    },
    "lod_d2_s016": {
        "id": "lod_d2_s016",
        "level": 4,
        "description": "-33% к шансу попадания",
        "learn_hell": 800,
        "learn_life": 400,
        "learn_death": 400,
        "learn_rune": 0,
        "learn_nature": 0,
        "use_hell": 100,
        "use_life": 200,
        "use_death": 100,
        "use_rune": 0,
        "use_nature": 0,

        "learned": 0,
    },
    "lod_d2_s017": {
        "id": "lod_d2_s017",
        "level": 4,
        "description": "75 урона огнем",
        "learn_hell": 800,
        "learn_life": 400,
        "learn_death": 400,
        "learn_rune": 0,
        "learn_nature": 0,
        "use_hell": 100,
        "use_life": 200,
        "use_death": 100,
        "use_rune": 0,
        "use_nature": 0,

        "learned": 0,
    },
    "lod_d2_s018": {
        "id": "lod_d2_s018",
        "level": 4,
        "description": "75 урона землей",
        "learn_hell": 800,
        "learn_life": 300,
        "learn_death": 500,
        "learn_rune": 0,
        "learn_nature": 0,
        "use_hell": 200,
        "use_life": 75,
        "use_death": 125,
        "use_rune": 0,
        "use_nature": 0,

        "learned": 0,
    },
    "lod_d2_s019": {
        "id": "lod_d2_s019",
        "level": 4,
        "description": "60 урона огнем по центру области",
        "learn_hell": 1200,
        "learn_life": 600,
        "learn_death": 600,
        "learn_rune": 0,
        "learn_nature": 0,
        "use_hell": 400,
        "use_life": 200,
        "use_death": 200,
        "use_rune": 0,
        "use_nature": 0,

        "learned": 0,
    },
    "lod_d2_s020": {
        "id": "lod_d2_s020",
        "level": 4,
        "description": "-33% инициативы в области, только для магов",
        "learn_hell": 1200,
        "learn_life": 600,
        "learn_death": 600,
        "learn_rune": 0,
        "learn_nature": 0,
        "use_hell": 300,
        "use_life": 150,
        "use_death": 150,
        "use_rune": 0,
        "use_nature": 0,

        "learned": 0,
    },
    "lod_d2_s021": {
        "id": "lod_d2_s021",
        "level": 5,
        "description": "Призыв адского мстителя",
        "learn_hell": 625,
        "learn_life": 200,
        "learn_death": 275,
        "learn_rune": 150,
        "learn_nature": 0,
        "use_hell": 250,
        "use_life": 80,
        "use_death": 110,
        "use_rune": 60,
        "use_nature": 0,

        "learned": 0,
    },
    "lod_d2_s022": {
        "id": "lod_d2_s022",
        "level": 5,
        "description": "Призыв иллюзии адского мстителя",
        "learn_hell": 250,
        "learn_life": 0,
        "learn_death": 0,
        "learn_rune": 0,
        "learn_nature": 0,
        "use_hell": 200,
        "use_life": 0,
        "use_death": 0,
        "use_rune": 0,
        "use_nature": 0,

        "learned": 0,
    },
    "lod_d2_s023": {
        "id": "lod_d2_s023",
        "level": 5,
        "description": "125 урона огнем",
        "learn_hell": 625,
        "learn_life": 175,
        "learn_death": 200,
        "learn_rune": 250,
        "learn_nature": 0,
        "use_hell": 250,
        "use_life": 70,
        "use_death": 80,
        "use_rune": 100,
        "use_nature": 0,

        "learned": 0,
    },
    "lod_d2_s024": {
        "id": "lod_d2_s024",
        "level": 5,
        "description": "Все отряды игрока становятся невидимыми до первого действия",
        "learn_hell": 1250,
        "learn_life": 400,
        "learn_death": 450,
        "learn_rune": 400,
        "learn_nature": 0,
        "use_hell": 500,
        "use_life": 160,
        "use_death": 180,
        "use_rune": 160,
        "use_nature": 0,

        "learned": 0,
    },
}


# Альянс Эльфов (DII)
elves_spells_d2 = {
    "elf_d2_s001": {
        "id": "elf_d2_s001",
        "level": 1,
        "description": "Наносит выбранным юнитам 15 единиц урона магией Земли",
        "learn_hell": 0,
        "learn_life": 0,
        "learn_death": 0,
        "learn_rune": 0,
        "learn_nature": 200,
        "use_hell": 0,
        "use_life": 0,
        "use_death": 0,
        "use_rune": 0,
        "use_nature": 100,

        "learned": 0,
    },
    "elf_d2_s002": {
        "id": "elf_d2_s002",
        "level": 1,
        "description": "Призывает малого энта",
        "learn_hell": 0,
        "learn_life": 0,
        "learn_death": 0,
        "learn_rune": 0,
        "learn_nature": 200,
        "use_hell": 0,
        "use_life": 0,
        "use_death": 0,
        "use_rune": 0,
        "use_nature": 100,

        "learned": 0,
    },
    "elf_d2_s003": {
        "id": "elf_d2_s003",
        "level": 1,
        "description": "Отнимает у цели 30% единиц движения",
        "learn_hell": 0,
        "learn_life": 0,
        "learn_death": 0,
        "learn_rune": 0,
        "learn_nature": 200,
        "use_hell": 0,
        "use_life": 0,
        "use_death": 0,
        "use_rune": 0,
        "use_nature": 100,

        "learned": 0,
    },
    "elf_d2_s004": {
        "id": "elf_d2_s004",
        "level": 1,
        "description": "Под воздействием этого заклинания юниты восстанавливают 30% единиц движения",
        "learn_hell": 0,
        "learn_life": 0,
        "learn_death": 0,
        "learn_rune": 0,
        "learn_nature": 200,
        "use_hell": 0,
        "use_life": 0,
        "use_death": 0,
        "use_rune": 0,
        "use_nature": 100,

        "learned": 0,
    },
    "elf_d2_s005": {
        "id": "elf_d2_s005",
        "level": 1,
        "description": "Под действием этого заклинания получаемый юнитами урон уменьшается на 10%",
        "learn_hell": 0,
        "learn_life": 0,
        "learn_death": 0,
        "learn_rune": 0,
        "learn_nature": 200,
        "use_hell": 0,
        "use_life": 0,
        "use_death": 0,
        "use_rune": 0,
        "use_nature": 100,

        "learned": 0,
    },
    "elf_d2_s006": {
        "id": "elf_d2_s006",
        "level": 2,
        "description": "Восстанавливает 30 единиц здоровья",
        "learn_hell": 0,
        "learn_life": 0,
        "learn_death": 0,
        "learn_rune": 0,
        "learn_nature": 400,
        "use_hell": 0,
        "use_life": 0,
        "use_death": 0,
        "use_rune": 0,
        "use_nature": 200,

        "learned": 0,
    },
    "elf_d2_s007": {
        "id": "elf_d2_s007",
        "level": 2,
        "description": "Призывает могучего энта",
        "learn_hell": 0,
        "learn_life": 0,
        "learn_death": 0,
        "learn_rune": 0,
        "learn_nature": 400,
        "use_hell": 0,
        "use_life": 0,
        "use_death": 0,
        "use_rune": 0,
        "use_nature": 200,

        "learned": 0,
    },
    "elf_d2_s008": {
        "id": "elf_d2_s008",
        "level": 2,
        "description": "Наносит выбранным юнитам 30 единиц урона магией Огня",
        "learn_hell": 0,
        "learn_life": 0,
        "learn_death": 0,
        "learn_rune": 0,
        "learn_nature": 400,
        "use_hell": 0,
        "use_life": 0,
        "use_death": 0,
        "use_rune": 0,
        "use_nature": 200,

        "learned": 0,
    },
    "elf_d2_s009": {
        "id": "elf_d2_s009",
        "level": 2,
        "description": "Наносит выбранным юнитам 30 единиц урона магией Воды",
        "learn_hell": 0,
        "learn_life": 0,
        "learn_death": 0,
        "learn_rune": 0,
        "learn_nature": 400,
        "use_hell": 0,
        "use_life": 0,
        "use_death": 0,
        "use_rune": 0,
        "use_nature": 200,

        "learned": 0,
    },
    "elf_d2_s010": {
        "id": "elf_d2_s010",
        "level": 2,
        "description": "На 15% снижает инициативу выбранных юнитов",
        "learn_hell": 0,
        "learn_life": 0,
        "learn_death": 0,
        "learn_rune": 0,
        "learn_nature": 400,
        "use_hell": 0,
        "use_life": 0,
        "use_death": 0,
        "use_rune": 0,
        "use_nature": 200,

        "learned": 0,
    },
    "elf_d2_s011": {
        "id": "elf_d2_s011",
        "level": 3,
        "description": "Призывает небольшую рощу, замедляя продвижение сил противника",
        "learn_hell": 0,
        "learn_life": 450,
        "learn_death": 0,
        "learn_rune": 0,
        "learn_nature": 450,
        "use_hell": 0,
        "use_life": 150,
        "use_death": 0,
        "use_rune": 0,
        "use_nature": 150,

        "learned": 0,
    },
    "elf_d2_s012": {
        "id": "elf_d2_s012",
        "level": 3,
        "description": "Призывает великого энта",
        "learn_hell": 0,
        "learn_life": 450,
        "learn_death": 0,
        "learn_rune": 0,
        "learn_nature": 450,
        "use_hell": 0,
        "use_life": 150,
        "use_death": 0,
        "use_rune": 0,
        "use_nature": 150,

        "learned": 0,
    },
    "elf_d2_s013": {
        "id": "elf_d2_s013",
        "level": 3,
        "description": "Наносит выбранным юнитам 50 единиц урона магией Разума",
        "learn_hell": 0,
        "learn_life": 450,
        "learn_death": 0,
        "learn_rune": 0,
        "learn_nature": 450,
        "use_hell": 0,
        "use_life": 150,
        "use_death": 0,
        "use_rune": 0,
        "use_nature": 150,

        "learned": 0,
    },
    "elf_d2_s014": {
        "id": "elf_d2_s014",
        "level": 3,
        "description": "Восстанавливает 50 единиц здоровья в центре зоны действия заклинания",
        "learn_hell": 0,
        "learn_life": 450,
        "learn_death": 0,
        "learn_rune": 0,
        "learn_nature": 450,
        "use_hell": 0,
        "use_life": 225,
        "use_death": 0,
        "use_rune": 0,
        "use_nature": 225,

        "learned": 0,
    },
    "elf_d2_s015": {
        "id": "elf_d2_s015",
        "level": 3,
        "description": "Шанс попадания по противнику юнитами в зоне действия заклинания падает на 20%",
        "learn_hell": 0,
        "learn_life": 0,
        "learn_death": 450,
        "learn_rune": 0,
        "learn_nature": 450,
        "use_hell": 0,
        "use_life": 0,
        "use_death": 150,
        "use_rune": 0,
        "use_nature": 150,

        "learned": 0,
    },
    "elf_d2_s016": {
        "id": "elf_d2_s016",
        "level": 4,
        "description": "Наносит 60 единиц урона магией Земли в центр площади заклинания",
        "learn_hell": 0,
        "learn_life": 400,
        "learn_death": 0,
        "learn_rune": 400,
        "learn_nature": 800,
        "use_hell": 0,
        "use_life": 200,
        "use_death": 0,
        "use_rune": 200,
        "use_nature": 300,

        "learned": 0,
    },
    "elf_d2_s017": {
        "id": "elf_d2_s017",
        "level": 4,
        "description": "Наносит выбранным юнитам 75 единиц урона магией Воздуха",
        "learn_hell": 0,
        "learn_life": 400,
        "learn_death": 0,
        "learn_rune": 400,
        "learn_nature": 800,
        "use_hell": 0,
        "use_life": 100,
        "use_death": 0,
        "use_rune": 100,
        "use_nature": 200,

        "learned": 0,
    },
    "elf_d2_s018": {
        "id": "elf_d2_s018",
        "level": 4,
        "description": "Уменьшает броню выбранных юнитов на 80",
        "learn_hell": 0,
        "learn_life": 300,
        "learn_death": 450,
        "learn_rune": 0,
        "learn_nature": 800,
        "use_hell": 0,
        "use_life": 100,
        "use_death": 100,
        "use_rune": 0,
        "use_nature": 200,

        "learned": 0,
    },
    "elf_d2_s019": {
        "id": "elf_d2_s019",
        "level": 4,
        "description": "Уменьшает урон, наносимый юнитами в бою, на 33%",
        "learn_hell": 0,
        "learn_life": 300,
        "learn_death": 450,
        "learn_rune": 0,
        "learn_nature": 800,
        "use_hell": 0,
        "use_life": 100,
        "use_death": 100,
        "use_rune": 0,
        "use_nature": 200,

        "learned": 0,
    },
    "elf_d2_s020": {
        "id": "elf_d2_s020",
        "level": 4,
        "description": "Добавляет зачарованным юнитам 50 единиц здоровья",
        "learn_hell": 0,
        "learn_life": 600,
        "learn_death": 0,
        "learn_rune": 300,
        "learn_nature": 800,
        "use_hell": 0,
        "use_life": 200,
        "use_death": 0,
        "use_rune": 200,
        "use_nature": 400,

        "learned": 0,
    },
    "elf_d2_s021": {
        "id": "elf_d2_s021",
        "level": 5,
        "description": "Призывает лесного буйного энта",
        "learn_hell": 0,
        "learn_life": 250,
        "learn_death": 225,
        "learn_rune": 150,
        "learn_nature": 625,
        "use_hell": 0,
        "use_life": 110,
        "use_death": 80,
        "use_rune": 50,
        "use_nature": 250,

        "learned": 0,
    },
    "elf_d2_s022": {
        "id": "elf_d2_s022",
        "level": 5,
        "description": "Наносит выбранным юнитам 125 единиц урона магией Земли",
        "learn_hell": 0,
        "learn_life": 150,
        "learn_death": 250,
        "learn_rune": 225,
        "learn_nature": 625,
        "use_hell": 0,
        "use_life": 100,
        "use_death": 80,
        "use_rune": 70,
        "use_nature": 250,

        "learned": 0,
    },
    "elf_d2_s023": {
        "id": "elf_d2_s023",
        "level": 5,
        "description": "Разрушает выбранный жезл",
        "learn_hell": 0,
        "learn_life": 225,
        "learn_death": 250,
        "learn_rune": 150,
        "learn_nature": 625,
        "use_hell": 0,
        "use_life": 80,
        "use_death": 60,
        "use_rune": 110,
        "use_nature": 250,

        "learned": 0,
    },
    "elf_d2_s024": {
        "id": "elf_d2_s024",
        "level": 5,
        "description": "Призывает обширный лес, замедляя продвижение сил противника. Более того, этот лес не будет считаться частью чьей-либо земли, как и горы с водой",
        "learn_hell": 0,
        "learn_life": 275,
        "learn_death": 150,
        "learn_rune": 200,
        "learn_nature": 625,
        "use_hell": 0,
        "use_life": 110,
        "use_death": 60,
        "use_rune": 60,
        "use_nature": 275,

        "learned": 0,
    },
}
