# enemy_configs.py
"""
RED команды для Campaign Mode.
Состав задан фиксированными отрядами.
"""

# ============================================================
# КОМАНДА 1: Орк
# ============================================================
ENEMY_TEAM_1 = [
    {
        'name': 'Орк',
        'initiative': 40,
        'initiative_base': 40,
        'team': 'red',
        'position': 1,
        'stand': 'ahead',
        'unit_type': 'Warrior',
        'damage': 55,
        'damage_secondary': 0,
        'health': 200,
        'max_health': 200,
        'armor': 0,
        'accuracy': 80,
        'accuracy_secondary': 0,
        'immunity': [],
        'resistance': [],
        'attack_type_primary': 'Weapon',
        'attack_type_secondary': '',
        'big': False,
        'paralyzed': 0,
        'long_paralyzed': 0,
        'running_away': 0,
        'transformed': 0,
        'basestats': [],
        'exp_kill': 90,
        'exp_required': 700,
        'exp_current': 0,
        'turns_into': []
    },
    {
        'name': 'Скваер',
        'initiative': 50,
        'initiative_base': 50,
        'team': 'red',
        'position': 2,
        'stand': 'ahead',
        'unit_type': 'Warrior',
        'damage': 25,
        'damage_secondary': 0,
        'health': 100,
        'max_health': 100,
        'armor': 0,
        'accuracy': 80,
        'accuracy_secondary': 0,
        'immunity': [],
        'resistance': [],
        'attack_type_primary': 'Weapon',
        'attack_type_secondary': '',
        'big': False,
        'paralyzed': 0,
        'long_paralyzed': 0,
        'running_away': 0,
        'transformed': 0,
        'basestats': [],
        'exp_kill': 20,
        'exp_required': 80,
        'exp_current': 0,
        'turns_into': ['Рыцарь', 'Охотник на ведьм']
    },
    {
        'name': 'пусто',
        'initiative': 0,
        'initiative_base': 0,
        'team': 'red',
        'position': 3,
        'stand': 'ahead',
        'unit_type': 'Archer',
        'damage': 0,
        'damage_secondary': 0,
        'health': 0,
        'max_health': 0,
        'armor': 0,
        'accuracy': 0,
        'accuracy_secondary': 0,
        'immunity': [],
        'resistance': [],
        'attack_type_primary': 'Weapon',
        'attack_type_secondary': '',
        'big': False,
        'paralyzed': 0,
        'long_paralyzed': 0,
        'running_away': 0,
        'transformed': 0,
        'basestats': [],
        'exp_kill': 0,
        'exp_required': 0,
        'exp_current': 0,
        'turns_into': []
    },
    {
        'name': 'Орк',
        'initiative': 40,
        'initiative_base': 40,
        'team': 'red',
        'position': 4,
        'stand': 'behind',
        'unit_type': 'Warrior',
        'damage': 55,
        'damage_secondary': 0,
        'health': 200,
        'max_health': 200,
        'armor': 0,
        'accuracy': 80,
        'accuracy_secondary': 0,
        'immunity': [],
        'resistance': [],
        'attack_type_primary': 'Weapon',
        'attack_type_secondary': '',
        'big': False,
        'paralyzed': 0,
        'long_paralyzed': 0,
        'running_away': 0,
        'transformed': 0,
        'basestats': [],
        'exp_kill': 90,
        'exp_required': 700,
        'exp_current': 0,
        'turns_into': []
    },
    {
        'name': 'пусто',
        'initiative': 0,
        'initiative_base': 0,
        'team': 'red',
        'position': 5,
        'stand': 'behind',
        'unit_type': 'Archer',
        'damage': 0,
        'damage_secondary': 0,
        'health': 0,
        'max_health': 0,
        'armor': 0,
        'accuracy': 0,
        'accuracy_secondary': 0,
        'immunity': [],
        'resistance': [],
        'attack_type_primary': 'Weapon',
        'attack_type_secondary': '',
        'big': False,
        'paralyzed': 0,
        'long_paralyzed': 0,
        'running_away': 0,
        'transformed': 0,
        'basestats': [],
        'exp_kill': 0,
        'exp_required': 0,
        'exp_current': 0,
        'turns_into': []
    },
    {
        'name': 'пусто',
        'initiative': 0,
        'initiative_base': 0,
        'team': 'red',
        'position': 6,
        'stand': 'behind',
        'unit_type': 'Archer',
        'damage': 0,
        'damage_secondary': 0,
        'health': 0,
        'max_health': 0,
        'armor': 0,
        'accuracy': 0,
        'accuracy_secondary': 0,
        'immunity': [],
        'resistance': [],
        'attack_type_primary': 'Weapon',
        'attack_type_secondary': '',
        'big': False,
        'paralyzed': 0,
        'long_paralyzed': 0,
        'running_away': 0,
        'transformed': 0,
        'basestats': [],
        'exp_kill': 0,
        'exp_required': 0,
        'exp_current': 0,
        'turns_into': []
    },
]

# ============================================================
# КОМАНДА 2: Орк + гоблин + гоблин-лучник
# ============================================================
ENEMY_TEAM_2 = [
    {
        'name': 'Орк',
        'initiative': 40,
        'initiative_base': 40,
        'team': 'red',
        'position': 1,
        'stand': 'ahead',
        'unit_type': 'Warrior',
        'damage': 55,
        'damage_secondary': 0,
        'health': 200,
        'max_health': 200,
        'armor': 0,
        'accuracy': 80,
        'accuracy_secondary': 0,
        'immunity': [],
        'resistance': [],
        'attack_type_primary': 'Weapon',
        'attack_type_secondary': '',
        'big': False,
        'paralyzed': 0,
        'long_paralyzed': 0,
        'running_away': 0,
        'transformed': 0,
        'basestats': [],
        'exp_kill': 90,
        'exp_required': 700,
        'exp_current': 0,
        'turns_into': []
    },
    {
        'name': 'Гоблин',
        'initiative': 30,
        'initiative_base': 30,
        'team': 'red',
        'position': 2,
        'stand': 'ahead',
        'unit_type': 'Warrior',
        'damage': 15,
        'damage_secondary': 0,
        'health': 50,
        'max_health': 50,
        'armor': 0,
        'accuracy': 80,
        'accuracy_secondary': 0,
        'immunity': [],
        'resistance': [],
        'attack_type_primary': 'Weapon',
        'attack_type_secondary': '',
        'big': False,
        'paralyzed': 0,
        'long_paralyzed': 0,
        'running_away': 0,
        'transformed': 0,
        'basestats': [],
        'exp_kill': 5,
        'exp_required': 50,
        'exp_current': 0,
        'turns_into': []
    },
    {
        'name': 'Гоблин',
        'initiative': 30,
        'initiative_base': 30,
        'team': 'red',
        'position': 3,
        'stand': 'ahead',
        'unit_type': 'Warrior',
        'damage': 15,
        'damage_secondary': 0,
        'health': 50,
        'max_health': 50,
        'armor': 0,
        'accuracy': 80,
        'accuracy_secondary': 0,
        'immunity': [],
        'resistance': [],
        'attack_type_primary': 'Weapon',
        'attack_type_secondary': '',
        'big': False,
        'paralyzed': 0,
        'long_paralyzed': 0,
        'running_away': 0,
        'transformed': 0,
        'basestats': [],
        'exp_kill': 5,
        'exp_required': 50,
        'exp_current': 0,
        'turns_into': []
    },
    {
        'name': 'Гоблин лучник',
        'initiative': 50,
        'initiative_base': 50,
        'team': 'red',
        'position': 4,
        'stand': 'behind',
        'unit_type': 'Archer',
        'damage': 15,
        'damage_secondary': 0,
        'health': 40,
        'max_health': 40,
        'armor': 0,
        'accuracy': 80,
        'accuracy_secondary': 0,
        'immunity': [],
        'resistance': [],
        'attack_type_primary': 'Weapon',
        'attack_type_secondary': '',
        'big': False,
        'paralyzed': 0,
        'long_paralyzed': 0,
        'running_away': 0,
        'transformed': 0,
        'basestats': [],
        'exp_kill': 10,
        'exp_required': 75,
        'exp_current': 0,
        'turns_into': []
    },
    {
        'name': 'Скваер',
        'initiative': 50,
        'initiative_base': 50,
        'team': 'red',
        'position': 5,
        'stand': 'behind',
        'unit_type': 'Warrior',
        'damage': 25,
        'damage_secondary': 0,
        'health': 100,
        'max_health': 100,
        'armor': 0,
        'accuracy': 80,
        'accuracy_secondary': 0,
        'immunity': [],
        'resistance': [],
        'attack_type_primary': 'Weapon',
        'attack_type_secondary': '',
        'big': False,
        'paralyzed': 0,
        'long_paralyzed': 0,
        'running_away': 0,
        'transformed': 0,
        'basestats': [],
        'exp_kill': 20,
        'exp_required': 80,
        'exp_current': 0,
        'turns_into': ['Рыцарь', 'Охотник на ведьм']
    },
    {
        'name': 'пусто',
        'initiative': 0,
        'initiative_base': 0,
        'team': 'red',
        'position': 6,
        'stand': 'behind',
        'unit_type': 'Archer',
        'damage': 0,
        'damage_secondary': 0,
        'health': 0,
        'max_health': 0,
        'armor': 0,
        'accuracy': 0,
        'accuracy_secondary': 0,
        'immunity': [],
        'resistance': [],
        'attack_type_primary': 'Weapon',
        'attack_type_secondary': '',
        'big': False,
        'paralyzed': 0,
        'long_paralyzed': 0,
        'running_away': 0,
        'transformed': 0,
        'basestats': [],
        'exp_kill': 0,
        'exp_required': 0,
        'exp_current': 0,
        'turns_into': []
    },
]

# ============================================================
# КОМАНДА 3: Орк + 2 гоблина (орк в центре)
# ============================================================
ENEMY_TEAM_3 = [
    {
        'name': 'Гоблин',
        'initiative': 30,
        'initiative_base': 30,
        'team': 'red',
        'position': 1,
        'stand': 'ahead',
        'unit_type': 'Warrior',
        'damage': 15,
        'damage_secondary': 0,
        'health': 50,
        'max_health': 50,
        'armor': 0,
        'accuracy': 80,
        'accuracy_secondary': 0,
        'immunity': [],
        'resistance': [],
        'attack_type_primary': 'Weapon',
        'attack_type_secondary': '',
        'big': False,
        'paralyzed': 0,
        'long_paralyzed': 0,
        'running_away': 0,
        'transformed': 0,
        'basestats': [],
        'exp_kill': 5,
        'exp_required': 50,
        'exp_current': 0,
        'turns_into': []
    },
    {
        'name': 'Орк',
        'initiative': 40,
        'initiative_base': 40,
        'team': 'red',
        'position': 2,
        'stand': 'ahead',
        'unit_type': 'Warrior',
        'damage': 55,
        'damage_secondary': 0,
        'health': 200,
        'max_health': 200,
        'armor': 0,
        'accuracy': 80,
        'accuracy_secondary': 0,
        'immunity': [],
        'resistance': [],
        'attack_type_primary': 'Weapon',
        'attack_type_secondary': '',
        'big': False,
        'paralyzed': 0,
        'long_paralyzed': 0,
        'running_away': 0,
        'transformed': 0,
        'basestats': [],
        'exp_kill': 90,
        'exp_required': 700,
        'exp_current': 0,
        'turns_into': []
    },
    {
        'name': 'Гоблин',
        'initiative': 30,
        'initiative_base': 30,
        'team': 'red',
        'position': 3,
        'stand': 'ahead',
        'unit_type': 'Warrior',
        'damage': 15,
        'damage_secondary': 0,
        'health': 50,
        'max_health': 50,
        'armor': 0,
        'accuracy': 80,
        'accuracy_secondary': 0,
        'immunity': [],
        'resistance': [],
        'attack_type_primary': 'Weapon',
        'attack_type_secondary': '',
        'big': False,
        'paralyzed': 0,
        'long_paralyzed': 0,
        'running_away': 0,
        'transformed': 0,
        'basestats': [],
        'exp_kill': 5,
        'exp_required': 50,
        'exp_current': 0,
        'turns_into': []
    },
    {
        'name': 'Скваер',
        'initiative': 50,
        'initiative_base': 50,
        'team': 'red',
        'position': 4,
        'stand': 'behind',
        'unit_type': 'Warrior',
        'damage': 25,
        'damage_secondary': 0,
        'health': 100,
        'max_health': 100,
        'armor': 0,
        'accuracy': 80,
        'accuracy_secondary': 0,
        'immunity': [],
        'resistance': [],
        'attack_type_primary': 'Weapon',
        'attack_type_secondary': '',
        'big': False,
        'paralyzed': 0,
        'long_paralyzed': 0,
        'running_away': 0,
        'transformed': 0,
        'basestats': [],
        'exp_kill': 20,
        'exp_required': 80,
        'exp_current': 0,
        'turns_into': ['Рыцарь', 'Охотник на ведьм']
    },
    {
        'name': 'пусто',
        'initiative': 0,
        'initiative_base': 0,
        'team': 'red',
        'position': 5,
        'stand': 'behind',
        'unit_type': 'Archer',
        'damage': 0,
        'damage_secondary': 0,
        'health': 0,
        'max_health': 0,
        'armor': 0,
        'accuracy': 0,
        'accuracy_secondary': 0,
        'immunity': [],
        'resistance': [],
        'attack_type_primary': 'Weapon',
        'attack_type_secondary': '',
        'big': False,
        'paralyzed': 0,
        'long_paralyzed': 0,
        'running_away': 0,
        'transformed': 0,
        'basestats': [],
        'exp_kill': 0,
        'exp_required': 0,
        'exp_current': 0,
        'turns_into': []
    },
    {
        'name': 'пусто',
        'initiative': 0,
        'initiative_base': 0,
        'team': 'red',
        'position': 6,
        'stand': 'behind',
        'unit_type': 'Archer',
        'damage': 0,
        'damage_secondary': 0,
        'health': 0,
        'max_health': 0,
        'armor': 0,
        'accuracy': 0,
        'accuracy_secondary': 0,
        'immunity': [],
        'resistance': [],
        'attack_type_primary': 'Weapon',
        'attack_type_secondary': '',
        'big': False,
        'paralyzed': 0,
        'long_paralyzed': 0,
        'running_away': 0,
        'transformed': 0,
        'basestats': [],
        'exp_kill': 0,
        'exp_required': 0,
        'exp_current': 0,
        'turns_into': []
    },
]

# ============================================================
# КОМАНДА 4: 3 орка на передней линии
# ============================================================
ENEMY_TEAM_4 = [
    {
        'name': 'Орк',
        'initiative': 40,
        'initiative_base': 40,
        'team': 'red',
        'position': 1,
        'stand': 'ahead',
        'unit_type': 'Warrior',
        'damage': 55,
        'damage_secondary': 0,
        'health': 200,
        'max_health': 200,
        'armor': 0,
        'accuracy': 80,
        'accuracy_secondary': 0,
        'immunity': [],
        'resistance': [],
        'attack_type_primary': 'Weapon',
        'attack_type_secondary': '',
        'big': False,
        'paralyzed': 0,
        'long_paralyzed': 0,
        'running_away': 0,
        'transformed': 0,
        'basestats': [],
        'exp_kill': 90,
        'exp_required': 700,
        'exp_current': 0,
        'turns_into': []
    },
    {
        'name': 'Гоблин',
        'initiative': 30,
        'initiative_base': 30,
        'team': 'red',
        'position': 2,
        'stand': 'ahead',
        'unit_type': 'Warrior',
        'damage': 15,
        'damage_secondary': 0,
        'health': 50,
        'max_health': 50,
        'armor': 0,
        'accuracy': 80,
        'accuracy_secondary': 0,
        'immunity': [],
        'resistance': [],
        'attack_type_primary': 'Weapon',
        'attack_type_secondary': '',
        'big': False,
        'paralyzed': 0,
        'long_paralyzed': 0,
        'running_away': 0,
        'transformed': 0,
        'basestats': [],
        'exp_kill': 5,
        'exp_required': 50,
        'exp_current': 0,
        'turns_into': []
    },
    {
        'name': 'Орк',
        'initiative': 40,
        'initiative_base': 40,
        'team': 'red',
        'position': 3,
        'stand': 'ahead',
        'unit_type': 'Warrior',
        'damage': 55,
        'damage_secondary': 0,
        'health': 200,
        'max_health': 200,
        'armor': 0,
        'accuracy': 80,
        'accuracy_secondary': 0,
        'immunity': [],
        'resistance': [],
        'attack_type_primary': 'Weapon',
        'attack_type_secondary': '',
        'big': False,
        'paralyzed': 0,
        'long_paralyzed': 0,
        'running_away': 0,
        'transformed': 0,
        'basestats': [],
        'exp_kill': 90,
        'exp_required': 700,
        'exp_current': 0,
        'turns_into': []
    },
    {
        'name': 'пусто',
        'initiative': 0,
        'initiative_base': 0,
        'team': 'red',
        'position': 4,
        'stand': 'behind',
        'unit_type': 'Archer',
        'damage': 0,
        'damage_secondary': 0,
        'health': 0,
        'max_health': 0,
        'armor': 0,
        'accuracy': 0,
        'accuracy_secondary': 0,
        'immunity': [],
        'resistance': [],
        'attack_type_primary': 'Weapon',
        'attack_type_secondary': '',
        'big': False,
        'paralyzed': 0,
        'long_paralyzed': 0,
        'running_away': 0,
        'transformed': 0,
        'basestats': [],
        'exp_kill': 0,
        'exp_required': 0,
        'exp_current': 0,
        'turns_into': []
    },
    {
        'name': 'пусто',
        'initiative': 0,
        'initiative_base': 0,
        'team': 'red',
        'position': 5,
        'stand': 'behind',
        'unit_type': 'Archer',
        'damage': 0,
        'damage_secondary': 0,
        'health': 0,
        'max_health': 0,
        'armor': 0,
        'accuracy': 0,
        'accuracy_secondary': 0,
        'immunity': [],
        'resistance': [],
        'attack_type_primary': 'Weapon',
        'attack_type_secondary': '',
        'big': False,
        'paralyzed': 0,
        'long_paralyzed': 0,
        'running_away': 0,
        'transformed': 0,
        'basestats': [],
        'exp_kill': 0,
        'exp_required': 0,
        'exp_current': 0,
        'turns_into': []
    },
    {
        'name': 'пусто',
        'initiative': 0,
        'initiative_base': 0,
        'team': 'red',
        'position': 6,
        'stand': 'behind',
        'unit_type': 'Archer',
        'damage': 0,
        'damage_secondary': 0,
        'health': 0,
        'max_health': 0,
        'armor': 0,
        'accuracy': 0,
        'accuracy_secondary': 0,
        'immunity': [],
        'resistance': [],
        'attack_type_primary': 'Weapon',
        'attack_type_secondary': '',
        'big': False,
        'paralyzed': 0,
        'long_paralyzed': 0,
        'running_away': 0,
        'transformed': 0,
        'basestats': [],
        'exp_kill': 0,
        'exp_required': 0,
        'exp_current': 0,
        'turns_into': []
    },
]

ENEMY_CONFIGS = {
    1: ENEMY_TEAM_1,
    2: ENEMY_TEAM_2,
    3: ENEMY_TEAM_3,
    4: ENEMY_TEAM_4,
}

# Описания для логов/визуализации
ENEMY_DESCRIPTIONS = {
    1: "Отряд: Орк, скваер и орк",
    2: "Отряд: Орк, 2 гоблина и гоблин-лучник",
    3: "Отряд: Орк и 2 гоблина",
    4: "Отряд: 3 орка на передней линии",
}
